insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (1, 'Alpha', 'Encounter for surgical aftercare following surgery on the circulatory system', 'Ultrasound Therapy of Heart, Multiple', 'Removal of Radioactive Element from Esophagus, Open Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (2, 'Tampflex', 'Syphilis of other musculoskeletal tissue', 'Excision of Right Main Bronchus, Via Natural or Artificial Opening Endoscopic', 'Drainage of Right Anterior Tibial Artery, Percutaneous Approach, Diagnostic', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (3, 'Regrant', 'Abnormal level of hormones in specimens from female genital organs', 'Nuclear Medicine, Gastrointestinal System, Tomographic (Tomo) Nuclear Medicine Imaging', 'Removal of Extraluminal Device from Lower Intestinal Tract, Percutaneous Endoscopic Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (4, 'Fix San', 'Other contact with nonvenomous snake, initial encounter', 'Removal of Internal Fixation Device from Left Carpal Joint, Percutaneous Endoscopic Approach', 'Revision of Drainage Device in Coccygeal Joint, Open Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (5, 'Kanlam', 'Acute inflammatory disease of uterus', 'Occlusion of Left Femoral Artery with Extraluminal Device, Open Approach', 'Bypass Esophagus to Cutaneous with Nonautologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (6, 'Matsoft', 'Fracture of posterior column [ilioischial] of acetabulum', 'Bypass Coronary Artery, One Artery from Aorta with Autologous Arterial Tissue, Open Approach', 'Drainage of Left Axilla, Percutaneous Approach, Diagnostic', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (7, 'Greenlam', 'Nondisplaced fracture of trapezium [larger multangular], unspecified wrist, subsequent encounter for fracture with delayed healing', 'Restriction of Left Common Iliac Vein, Percutaneous Endoscopic Approach', 'Supplement Left Kidney Pelvis with Autologous Tissue Substitute, Open Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (8, 'Alpha', 'Other forms of chronic ischemic heart disease', 'Destruction of Thoracolumbar Vertebral Disc, Percutaneous Approach', 'Fragmentation in Common Bile Duct, Percutaneous Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (9, 'Aerified', 'Nondisplaced fracture of lateral end of right clavicle, initial encounter for closed fracture', 'Removal of Drainage Device from Lower Muscle, Percutaneous Endoscopic Approach', 'Revision of Infusion Device in Upper Vein, External Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');
insert into SPRINT (sprint_id, name, description, review_details, retro_details, start_date, end_date, date_created, status, timestamp) values (10, 'Voyatouch', 'Nondisplaced comminuted fracture of shaft of ulna, right arm, initial encounter for closed fracture', 'Transfer Right Foot Skin, External Approach', 'Dilation of Right Internal Mammary Artery with Three Intraluminal Devices, Percutaneous Endoscopic Approach', '2019-08-10', '2019-07-31', '2019-08-12', 'IDR', '2019-04-20');

insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (1, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (2, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (3, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (4, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (5, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (6, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (7, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');
insert into USERSTORY (userstory_id, title, description, summary, priority, storypoint, status) values (8, 'Flexidy', 'Malignant neoplasm of long bones of left lower limb', 'Fluoroscopy Intercos/Bronc A w L Osm Contrast, Laser Intraop', 'application/pdf', 1, 'mastercard');

